//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;


public class GameController : MonoBehaviour
{


	public GameObject enemy1;
	public GameObject enemy2;

	public GameObject friend1;

	public GameObject gameOverMsg;
	public GameObject gameWonMsg;

	public bool enemy1present;
	public bool enemy2present;
	public bool friend1present;
	private bool isIntCached;


	void Awake(){
		if (enemy1 != null) {
			enemy1present = true;
		} else {
			enemy1present = false;
		}
		if (enemy2 != null) {
			enemy2present = true;
		} else {
			enemy2present = false;
		}

		if (friend1 != null) {
			friend1present = true;
		} else {
			friend1present = false;
		}

		gameOverMsg.SetActive(false);
		gameWonMsg.SetActive(false);


	}

	void Update() {

		if (friend1present && (friend1 == null)) { // was present now it is destroyed
			gameOverMsg.SetActive (true);
			StartCoroutine("ReloadGame");
		} else {
			if (enemy1present && enemy2present) {
				if ((enemy1 == null) && (enemy2 == null)) {
					gameWonMsg.SetActive(true);
					StartCoroutine("ReloadGame");
				}
			}
			else if (enemy1present && !enemy2present) {
				if (enemy1 == null) {
					gameWonMsg.SetActive(true);
					StartCoroutine("ReloadGame");
				}
			}
			else if (!enemy1present && enemy2present) {
				if (enemy2 == null) {
					gameWonMsg.SetActive(true);
					StartCoroutine("ReloadGame");
				}
			}
		}
	
	}

	IEnumerator ReloadGame()
	{			
		// ... pause briefly
	
		yield return new WaitForSeconds(2);
		
		// ... and then reload the level.
		//Application.LoadLevel(Application.loadedLevel);
		Application.LoadLevel ("gamemenu");
	}

}

