//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections;

public class SpaceGun : MonoBehaviour
{


	public Rigidbody2D bullet;
	public float bulletSpeed = 20f;
	public float range = 30f;
	public float distance;
	private float bulletTimer = 0f;
	public float shootInterval = 1f;
	public int gunof = 1; //1 is friend, 2is enemy
	public bool enemyGun = true;
	public Transform attackingtrans;
	void Awake()
	{
		// Setting up the references.
		//anim = transform.root.gameObject.GetComponent<Animator>();
		//playerCtrl = transform.root.GetComponent<PlayerControl>();
		//InvokeRepeating("LaunchProjectile", 1.0f, 0.4f);
		
	}
	

	void Update ()
	{
		// If the fire button is pressed...
		if (transform.tag == "EnemyGun") {

				if (attackingtrans != null) {
					distance = Vector2.Distance (transform.position, attackingtrans.transform.position);
					if (distance < range) {
						Attack (attackingtrans);
					}
				}
		
			 
		}
		/*else {
			tran = GameObject.FindGameObjectsWithTag("Player");
			foreach (GameObject tran1 in tran)
			{
				// ... and if it's beyond the left spawn position...
				distance = Vector2.Distance (transform.position, tran1.gameObject.transform.position);
				if (distance < range) {
					Attack (tran1.gameObject.transform);
				}

			}
		}
		*/
	}

	void OnTriggerEnter2D (Collider2D col) 
	{
		if (transform.tag == "EnemyGun") {
			// If it hits an enemy...
			if (col.tag == "Player") {
			//	intrusiondetected = true;
				Attack (col.transform);
				attackingtrans = col.transform;
			} else if (col.tag == "friendly") {
			//	intrusiondetected = true;
				Attack (col.transform);
				attackingtrans = col.transform;
			}
			// Otherwise if it hits a bomb crate...
			else if (col.tag == "Enemy") {
				
			//	intrusiondetected = false;
				
			}
		}
		else if (transform.tag == "friendlyGun") {
			// If it hits an enemy...
			if (col.tag == "Enemy") {
			//	intrusiondetected = true;
				Attack (col.transform);
				attackingtrans = col.transform;
			} else if (col.tag == "friendly") {
				//intrusiondetected = true;
				//takeDefense ("friendly");
			}
			// Otherwise if it hits a bomb crate...
			else if (col.tag == "Player") {
				//showInventory();
				//intrusiondetected = false;
				
			}
		}
	}


	public void Attack(Transform t1) {

		bulletTimer += Time.deltaTime;
		if (bulletTimer > shootInterval) {
			Vector2 direction = t1.transform.position - transform.position;
			direction.Normalize ();

			Rigidbody2D bulletInstance = Instantiate (bullet, transform.position, transform.rotation) as Rigidbody2D;
			bulletInstance.velocity = direction * bulletSpeed;
			bulletTimer = 0;
		}
	}

	
}
